services:
  tasks-frontend:
    image: ghcr.io/crazyscreamx/task-manager-frontend:latest
    container_name: tasks-frontend
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_URL=${BACKEND_URL}
    stdin_open: true
    tty: true
