services:
  tasks-api:
    image: ghcr.io/crazyscreamx/task-manager-backend:latest
    container_name: tasks-api
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${BACKEND_PORT}:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
