---

- name: Configuring NVA Machine
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - name: Allowing IP Forwwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Installing Cloudflare ZTNA Tunnel - Debian/Ubuntu
      block:
        - name: Making gpg keyrings directory
          ansible.builtin.file:
            path: /usr/share/keyrings
            state: directory
            mode: '0755'

        - name: Downloading Cloudflare GPG key
          ansible.builtin.get_url:
            url: https://pkg.cloudflare.com/cloudflare-main.gpg
            dest: /usr/share/keyrings/cloudflare-main.gpg
            mode: '0644'

        - name: Adding Cloudflare APT repository
          copy:
            dest: /etc/apt/sources.list.d/cloudflared.list
            content: "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main\n"
            owner: root
            group: root
            mode: '0644'

        - name: Updating APT package index
          ansible.builtin.apt:
            update_cache: yes


        - name: Installing Cloudflared
          ansible.builtin.apt:
            name: cloudflared
            state: present

        - name: Installing Cloudflared as a systemd service
          ansible.builtin.shell: "cloudflared service install {{ tunnel_token }}"

        - name: Configuring Cloudflare Tunnel
          ansible.builtin.systemd:
            name: cloudflared
            state: started
            enabled: true
            masked: false

    - name: Configuring UFW
      block:
        - name: Getting NVA IP
          shell: hostname -I
          register: nva_ip

        - name: Deny incoming traffic
          community.general.ufw:
            state: enabled
            policy: deny
            direction: incoming
        
        - name: Deny outgoing traffic
          community.general.ufw:
            policy: deny
            direction: outgoing
        
        - name: Deny routed traffic
          community.general.ufw:
            policy: deny
            direction: routed

        - name: Allow access from Frontend Subnet to Load Balancer
          community.general.ufw:
            rule: routed
            from: "{{ frontend_subnet }}"
            to: "{{ lb_ip }}"
            port: "{{ backend_port }}"
            proto: tcp
        
        - name: Allow outgoing SSH to backend (Port 22)
          community.general.ufw:
            rule: allow
            from: "{{ nva_ip.stdout }}"
            to: "{{ backend_subnet }}"
            port: 22
            proto: tcp
        
        - name: Allow outgoing SSH to Frontend
          community.general.ufw:
            rule: allow
            from: "{{ nva_ip.stdout }}"
            to: "{{ frontend_subnet }}"
            port: 22
            proto: tcp

        - name: Allow routed from Backend to Internet
          community.general.ufw:
            rule: allow
            routed: true
            from: "{{ backend_subnet }}"

        - name: Allow SSH
          community.general.ufw:
            rule: allow
            name: 'OpenSSH'

        - name: Reload UFW
          community.general.ufw:
            state: reloaded

    - name: Configuring NAT for Internet Access
      block:
        - name: Add iptables NAT rule for VNet traffic
          ansible.builtin.iptables:
            table: nat
            chain: POSTROUTING
            source: "{{ backend_subnet}}"
            out_interface: eth0
            jump: MASQUERADE
            state: present
      
        
        